language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t glowing-happiness -f Dockerfile.dev .

script:
  - docker run -e CI=true glowing-happiness npm run test -- --coverage
