language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t glowing-happiness -f Dockerfile.dev .

script:
  - docker run -e CI=true glowing-happiness npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "glowing-happiness"
  env: "Glowinghappiness-env"
  bucket_name: "elasticbeanstalk-eu-central-1-127748698469"
  bucket_path: "glowing-happiness"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"